### ISSUE TITLE
安装2.x依赖报错

### ISSUE THREAD

**Issue by birdycn** [alibaba/formily#1126]
npm install --save @formily/antd @formily/react @formily/react-schema-field

 Install fail! Error: GET https://r.npm.taobao.org/@formily%2Freact-schema-field response 404 status
Error: GET https://r.npm.taobao.org/@formily%2Freact-schema-field response 404 status
    at get (C:\Users\xxx\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\get.js:68:17)       
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\xxx\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npminstall version: 3.28.0

**Comment by birdycn** [comment]
react-schema-field 请问这个依赖应该怎么安装

**Comment by birdycn** [comment]
用2.x的示例代码

import { NumberPicker, FormItem, Space } from '@formily/antd'
import { createForm, FormProvider, FormConsumer, Field } from '@formily/react'

NumberPicker，Space，createForm，都提示没有导出的成员
